# Generated by Django 6.0.6 on 2026-10-09 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercalendar',
            name='teaching_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercalendar',
            name='teaching_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AcademicCalendarPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('period_type', models.CharField(choices=[('BREAK', 'Official Academic Break'), ('REVISION', 'Revision Period'), ('EXAM', 'Examination Period'), ('OTHER', 'Other Excluded Period')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academic_calendar.semestercalendar')),
            ],
            options={
                'ordering': ['start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='calendar_period_end_after_start')],
            },
        ),
    ]
