# Generated by Django 6.0.6 on 2026-10-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_classroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
