# Generated by Django 6.0.6 on 2026-10-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_classroom_altitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
